// src/components/Credit/index.tsx
import React from 'react';
import styles from './styles.module.css';

const Credit: React.FC = () => (
  <footer className={styles.footer}>
    <span>スマートフォン・タブレットで閲覧してください</span>
    <a
      className={styles.link}
      href="https://github.com/TinyKitten/SpeedometerPWA"
      target="_blank"
      rel="noreferrer"
    >
      Fork me on Github
    </a>
  </footer>
);

export default Credit;

// src/components/Credit.vue
<template>
  <footer>
      <span>スマートフォン・タブレットで閲覧してください</span>
      <a href="https://github.com/TinyKitten/SpeedometerPWA" target="_blank" rel="noreferrer">Fork me on Github</a>
  </footer>
</template>

<script>
export default {

};
</script>

<style scoped>
    footer {
        width: 100%;
        text-align: center;
        font-size: .9rem;
        line-height: 1.25rem;
        opacity: .75;
        margin-top: 32px;
    }
    a {
        display: block;
        color: #fff;
        text-align: center;
        text-decoration: none;
        font-weight: bold;
    }
</style>
